### ISSUE TITLE
Swing Probleme auf dem Mac? 

### ISSUE THREAD

**Issue by alex-meinecke** [matthiasbergneels/dhbwmawwi2022seb#11]
Hey,

hatten andere Mac-Nutzer heute auch Probleme mit Swing? Wenn ich eine Änderung im Code gemacht habe, wurde oft nur das leere Frame angezeigt. Der Inhalt wurde oft nur nach mehreren Starts der main-Methode sichtbar...

Weiß jemand, woran das liegt?

**Comment by matthiasbergneels** [comment]
Guten Morgen, 

auf meinem Mac gab es keine Probleme bisher. Wurde das Programm immer geschlossen oder war es noch im Dock aktiv?

**Comment by alex-meinecke** [comment]
Hallo,

das Programm wurde immer geschlossen. 

Ich habe jetzt nochmal eine zweite Version gebaut, aber auch hier bleibt das Problem bestehen. Es wird beim Start immer nur das leere Frame gezeigt. Wenn aber die Größe am Rahmen etwas verzogen wird, erscheint der Inhalt. Ich weiß nicht, ob es an meiner Java Version liegt oder ob ich vlt. doch irgendwo einen Fehler im Code habe.

Vielleicht probieren Sie mal, mein Programm auszuführen. Mein Branch ist S14 und mein aktuelles Logon liegt unter "_src/studentarea/excersises/chapter10/LogonPagev2.java_".

VG

<img width="434" alt="Screenshot 2023-06-23 at 23 26 22" src="https://github.com/matthiasbergneels/dhbwmawwi2022seb/assets/30233821/7c57cec5-65d5-4f8e-b187-be0d53caaeb9">
<img width="438" alt="Screenshot 2023-06-23 at 23 26 31" src="https://github.com/matthiasbergneels/dhbwmawwi2022seb/assets/30233821/9cc40c58-9629-4cb1-a0f9-4d8441e585be">

**Comment by alex-meinecke** [comment]
Problem geklärt!

Lösung: 
`logonPage.setVisible(true);` erst am Ende aufrufen. 

Wahrscheinlich rerendert das Fenster erst dann, wenn es in der Größe verzogen wird.
